wykonanie step 2 w zadaniu 1

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -1,10 +1,23 @@
 ---
 name: 01 – Building Blocks
-on: push
+on: 
+  push:
+  workflow_dispatch:
 
 jobs:
-  przywitaj_sie:
+  powitanie:
   runs-on: ubuntu-latest
   steps:
   - name: Say hello
     run: echo "Hello, World!"
+  
+  pozegnanie:
+  runs-on: ubuntu-latest
+  steps:
+  - name: Failed Step
+        run: |
+          echo "I will fail now"
+          exit 1
+      - name: Say Goodbye
+        run: |
+          echo "This step will be skipped if the previous step fails"
